services:
  - type: web
    name: hospital-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_FIREBASE_API_KEY
        fromService: false
      - key: VITE_FIREBASE_PROJECT_ID
        fromService: false
      - key: VITE_FIREBASE_APP_ID
        fromService: false