services:
  - type: web
    name: hospital-management-system
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyAcwXCNWt1bvWSbCmmJ1Fo0VEEDutnj6so
      - key: VITE_FIREBASE_PROJECT_ID
        value: dar1-23
      - key: VITE_FIREBASE_APP_ID
        value: 1:1015752030247:web:1fa3e73cfdaa129195f602